# Site settings
title: Ben-Hur
email: benhur.onrails@gmail.com
description: "Ben-Hur Batista, desenvolvedor Rails desde maio de 2012, trabalha atualmente na Xavante Sistemas, no desenvolvimento do Painel Gerenciador dos Parquimetros da Expark, e na página da mesma."
baseurl: ""
url: "http://hifenhur.github.io"
username: hifenhur

# Build settings
markdown: kramdown
permalink: pretty
